version: "3.9"

services:
  database:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nous_dev
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  web:
    build: .
    depends_on:
      - database
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=ecto://postgres:postgres@database:5432/nous_dev
      - SECRET_KEY_BASE=ZTdZFDTMJqgfUtZTKgtLnR/utjhdsUhObNlrgqHT5xG45nJDLcXGKES+FPjLXKUQ
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app

volumes:
  pgdata:
